'use strict';
module.exports.neeoCommands = function () {
  return {
    "POWER OFF":{"method": "System.Shutdown"},
    "POWER OFF Forced":{"method": "System.Shutdown"},
    "POWER ON":{"method": "WOL"},
    "POWER ON Forced":{"method": "WOL"},
    "PLAY":{"method": "Input.ExecuteAction","params":{ "action": "play"}},
    "PAUSE":{"method": "Input.ExecuteAction","params":{ "action": "pause"}},
    "STOP":{"method": "Input.ExecuteAction","params":{ "action": "stop"}},
    "SKIP BACKWARD":{"method": "Input.ExecuteAction","params":{ "action": "skipprevious"}},
    "SKIP FORWARD":{"method": "Input.ExecuteAction","params":{ "action": "skipnext"}},
    "FORWARD":{"method": "Player.SetSpeed", "params": {"playerid":1, "speed":2}, "id":1},
    "PREVIOUS":{"method": "Player.GoTo", "params": { "playerid":1, "to": "previous"}, "id":1},
    "NEXT":{"method": "Player.GoTo", "params": { "playerid":1, "to": "next"}, "id":1},
    "REVERSE":{"method": "Player.SetSpeed", "params": {"playerid":1, "speed":-2}, "id":1},
    "PLAY PAUSE TOGGLE":{"method": "Input.PlayPause"},
    "INFO":{"method": "Input.ExecuteAction","params":{ "action": "info"}},
    "CHANNEL UP":{"method": "Input.ExecuteAction","params":{ "action": "channelup"}},
    "CHANNEL DOWN":{"method": "Input.ExecuteAction","params":{ "action": "channeldown"}},
    "CHANNEL SEARCH":{"method": "Input.ExecuteAction","params":{ "action": "nextchannelgroup"}},
    "FAVORITE":{"method":"GUI.ActivateWindow","params":{"window":"pvrosdchannels"}},
    "DIGIT 0":{"method": "Input.ExecuteAction","params":{ "action": "number0"}},
    "DIGIT 1":{"method": "Input.ExecuteAction","params":{ "action": "number1"}},
    "DIGIT 2":{"method": "Input.ExecuteAction","params":{ "action": "number2"}},
    "DIGIT 3":{"method": "Input.ExecuteAction","params":{ "action": "number3"}},
    "DIGIT 4":{"method": "Input.ExecuteAction","params":{ "action": "number4"}},
    "DIGIT 5":{"method": "Input.ExecuteAction","params":{ "action": "number5"}},
    "DIGIT 6":{"method": "Input.ExecuteAction","params":{ "action": "number6"}},
    "DIGIT 7":{"method": "Input.ExecuteAction","params":{ "action": "number7"}},
    "DIGIT 8":{"method": "Input.ExecuteAction","params":{ "action": "number8"}},
    "DIGIT 9":{"method": "Input.ExecuteAction","params":{ "action": "number9"}},
    "DIGIT SEPARATOR":{"method": "Input.xxxx"},
    "BACK":{"method": "Input.Back"},
    "CURSOR DOWN":{"method": "Input.down"},
    "CURSOR LEFT":{"method": "Input.Left"},
    "CURSOR RIGHT":{"method": "Input.right"},
    "CURSOR UP":{"method": "Input.up"},
    "CURSOR ENTER":{"method": "Input.Select"},
    "EXIT":{"method": "Input.back"},
    "HOME":{"method": "Input.menu"},
    "MENU":{"method": "Input.ContextMenu"},
    "VOLUME UP":{"method": "Input.ExecuteAction","params":{ "action": "volumeup"}},
    "VOLUME DOWN":{"method": "Input.ExecuteAction","params":{ "action": "volumedown"}},
    "MUTE TOGGLE":{"method": "Input.ExecuteAction","params":{ "action": "mute"}},
    "Page Up":{"method": "Input.ExecuteAction","params":{ "action": "pageup"}},
    "Scan Video Library":{"method": "VideoLibrary.Scan"},
    "Scan Audio Library":{"method": "AudioLibrary.Scan"},
    "Page Down":{"method": "Input.ExecuteAction","params":{ "action": "pagedown"}},
    "Parent Dir":{"method": "Input.ExecuteAction","params":{ "action": "parentdir"}},
    "Parent Folder":{"method": "Input.ExecuteAction","params":{ "action": "parentfolder"}},
    "Previous Menu":{"method": "Input.ExecuteAction","params":{ "action": "previousmenu"}},
    "Fullscreen":{"method": "Input.ExecuteAction","params":{ "action": "fullscreen"}},
    "Aspectratio":{"method": "Input.ExecuteAction","params":{ "action": "aspectratio"}},
    "OSD":{"method": "Input.ExecuteAction","params":{ "action": "osd"}},
    "Show Subtitles":{"method": "Input.ExecuteAction","params":{ "action": "showsubtitles"}},
    "Next Subtitle":{"method": "Input.ExecuteAction","params":{ "action": "nextsubtitle"}},
    "Cycle Subtitle":{"method": "Input.ExecuteAction","params":{ "action": "cyclesubtitle"}},
    "Player Debug":{"method": "Input.ExecuteAction","params":{ "action": "playerdebug"}},
    "Codec Info":{"method": "Input.ExecuteAction","params":{ "action": "codecinfo"}},
    "Player Processinfo":{"method": "Input.ExecuteAction","params":{ "action": "playerprocessinfo"}},
    "Next Picture":{"method": "Input.ExecuteAction","params":{ "action": "nextpicture"}},
    "Previous Picture":{"method": "Input.ExecuteAction","params":{ "action": "previouspicture"}},
    "Zoomout":{"method": "Input.ExecuteAction","params":{ "action": "zoomout"}},
    "Zoomin":{"method": "Input.ExecuteAction","params":{ "action": "zoomin"}},
    "Playlist":{"method": "Input.ExecuteAction","params":{ "action": "playlist"}},
    "Queue":{"method": "Input.ExecuteAction","params":{ "action": "queue"}},
    "Zoom normal":{"method": "Input.ExecuteAction","params":{ "action": "zoomnormal"}},
    "Zoomlevel 1":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel1"}},
    "Zoomlevel 2":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel2"}},
    "Zoomlevel 3":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel3"}},
    "Zoomlevel 4":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel4"}},
    "Zoomlevel 5":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel5"}},
    "Zoomlevel 6":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel6"}},
    "Zoomlevel 7":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel7"}},
    "Zoomlevel 8":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel8"}},
    "Zoomlevel 9":{"method": "Input.ExecuteAction","params":{ "action": "zoomlevel9"}},
    "Next Calibration":{"method": "Input.ExecuteAction","params":{ "action": "nextcalibration"}},
    "Reset Calibration":{"method": "Input.ExecuteAction","params":{ "action": "resetcalibration"}},
    "Analog Move":{"method": "Input.ExecuteAction","params":{ "action": "analogmove"}},
    "Analog Move X":{"method": "Input.ExecuteAction","params":{ "action": "analogmovex"}},
    "Analog Move Y":{"method": "Input.ExecuteAction","params":{ "action": "analogmovey"}},
    "Rotate":{"method": "Input.ExecuteAction","params":{ "action": "rotate"}},
    "Rotate CCW":{"method": "Input.ExecuteAction","params":{ "action": "rotateccw"}},
    "Subtitledelay -":{"method": "Input.ExecuteAction","params":{ "action": "subtitledelayminus"}},
    "Subtitledelay":{"method": "Input.ExecuteAction","params":{ "action": "subtitledelay"}},
    "Subtitledelay +":{"method": "Input.ExecuteAction","params":{ "action": "subtitledelayplus"}},
    "Audiodelay -":{"method": "Input.ExecuteAction","params":{ "action": "audiodelayminus"}},
    "Audiodelay":{"method": "Input.ExecuteAction","params":{ "action": "audiodelay"}},
    "Audiodelay +":{"method": "Input.ExecuteAction","params":{ "action": "audiodelayplus"}},
    "Subtitle shift up":{"method": "Input.ExecuteAction","params":{ "action": "subtitleshiftup"}},
    "Subtitle shift down":{"method": "Input.ExecuteAction","params":{ "action": "subtitleshiftdown"}},
    "Subtitle align":{"method": "Input.ExecuteAction","params":{ "action": "subtitlealign"}},
    "Audio next language":{"method": "Input.ExecuteAction","params":{ "action": "audionextlanguage"}},
    "Vertical shift up":{"method": "Input.ExecuteAction","params":{ "action": "verticalshiftup"}},
    "Vertical shift down":{"method": "Input.ExecuteAction","params":{ "action": "verticalshiftdown"}},
    "Next resolution":{"method": "Input.ExecuteAction","params":{ "action": "nextresolution"}},
    "Audio toggle digita":{"method": "Input.ExecuteAction","params":{ "action": "audiotoggledigita"}},
    "Switch player":{"method": "Input.ExecuteAction","params":{ "action": "switchplayer"}},
    "Delete":{"method": "Input.ExecuteAction","params":{ "action": "delete"}},
    "Copy":{"method": "Input.ExecuteAction","params":{ "action": "copy"}},
    "Move":{"method": "Input.ExecuteAction","params":{ "action": "move"}},
    "Screenshot":{"method": "Input.ExecuteAction","params":{ "action": "screenshot"}},
    "Rename":{"method": "Input.ExecuteAction","params":{ "action": "rename"}},
    "Toggle watched":{"method": "Input.ExecuteAction","params":{ "action": "togglewatched"}},
    "Scan item":{"method": "Input.ExecuteAction","params":{ "action": "scanitem"}},
    "Reload keymaps":{"method": "Input.ExecuteAction","params":{ "action": "reloadkeymaps"}},
    "Scrollup":{"method": "Input.ExecuteAction","params":{ "action": "scrollup"}},
    "Scrolldown":{"method": "Input.ExecuteAction","params":{ "action": "scrolldown"}},
    "Analog fastforward":{"method": "Input.ExecuteAction","params":{ "action": "analogfastforward"}},
    "Analog rewind":{"method": "Input.ExecuteAction","params":{ "action": "analogrewind"}},
    "Move item up":{"method": "Input.ExecuteAction","params":{ "action": "moveitemup"}},
    "Move item down":{"method": "Input.ExecuteAction","params":{ "action": "moveitemdown"}},
    "Contextmenu":{"method": "Input.ExecuteAction","params":{ "action": "contextmenu"}},
    "Shift":{"method": "Input.ExecuteAction","params":{ "action": "shift"}},
    "Symbols":{"method": "Input.ExecuteAction","params":{ "action": "symbols"}},
    "Cursor left":{"method": "Input.ExecuteAction","params":{ "action": "cursorleft"}},
    "Cursor right":{"method": "Input.ExecuteAction","params":{ "action": "cursorright"}},
    "Showtime":{"method": "Input.ExecuteAction","params":{ "action": "showtime"}},
    "Analog seek forward":{"method": "Input.ExecuteAction","params":{ "action": "analogseekforward"}},
    "Analog seek back":{"method": "Input.ExecuteAction","params":{ "action": "analogseekback"}},
    "Show preset":{"method": "Input.ExecuteAction","params":{ "action": "showpreset"}},
    "Next preset":{"method": "Input.ExecuteAction","params":{ "action": "nextpreset"}},
    "Previous preset":{"method": "Input.ExecuteAction","params":{ "action": "previouspreset"}},
    "Lock preset":{"method": "Input.ExecuteAction","params":{ "action": "lockpreset"}},
    "Random preset":{"method": "Input.ExecuteAction","params":{ "action": "randompreset"}},
    "Increase vis rating":{"method": "Input.ExecuteAction","params":{ "action": "increasevisrating"}},
    "Decrease vis rating":{"method": "Input.ExecuteAction","params":{ "action": "decreasevisrating"}},
    "Show video menu":{"method": "Input.ExecuteAction","params":{ "action": "showvideomenu"}},
    "Increase rating":{"method": "Input.ExecuteAction","params":{ "action": "increaserating"}},
    "Decrease rating":{"method": "Input.ExecuteAction","params":{ "action": "decreaserating"}},
    "Set rating":{"method": "Input.ExecuteAction","params":{ "action": "setrating"}},
    "Toggle fullscreen":{"method": "Input.ExecuteAction","params":{ "action": "togglefullscreen"}},
    "Next letter":{"method": "Input.ExecuteAction","params":{ "action": "nextletter"}},
    "Prev letter":{"method": "Input.ExecuteAction","params":{ "action": "prevletter"}},
    "jump sms 2":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms2"}},
    "jump sms 3":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms3"}},
    "jump sms 4":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms4"}},
    "jump sms 5":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms5"}},
    "jump sms 6":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms6"}},
    "jump sms 7":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms7"}},
    "jump sms 8":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms8"}},
    "jump sms 9":{"method": "Input.ExecuteAction","params":{ "action": "jumpsms9"}},
    "Filter":{"method": "Input.ExecuteAction","params":{ "action": "filter"}},
    "Filter clear":{"method": "Input.ExecuteAction","params":{ "action": "filterclear"}},
    "filter sms 2":{"method": "Input.ExecuteAction","params":{ "action": "filtersms2"}},
    "filter sms 3":{"method": "Input.ExecuteAction","params":{ "action": "filtersms3"}},
    "filter sms 4":{"method": "Input.ExecuteAction","params":{ "action": "filtersms4"}},
    "filter sms 5":{"method": "Input.ExecuteAction","params":{ "action": "filtersms5"}},
    "filter sms 6":{"method": "Input.ExecuteAction","params":{ "action": "filtersms6"}},
    "filter sms 7":{"method": "Input.ExecuteAction","params":{ "action": "filtersms7"}},
    "filter sms 8":{"method": "Input.ExecuteAction","params":{ "action": "filtersms8"}},
    "filter sms 9":{"method": "Input.ExecuteAction","params":{ "action": "filtersms9"}},
    "Firstpage":{"method": "Input.ExecuteAction","params":{ "action": "firstpage"}},
    "Lastpage":{"method": "Input.ExecuteAction","params":{ "action": "lastpage"}},
    "GUI Profile":{"method": "Input.ExecuteAction","params":{ "action": "guiprofile"}},
    "Red":{"method": "Input.ExecuteAction","params":{ "action": "red"}},
    "Green":{"method": "Input.ExecuteAction","params":{ "action": "green"}},
    "Yellow":{"method": "Input.ExecuteAction","params":{ "action": "yellow"}},
    "Blue":{"method": "Input.ExecuteAction","params":{ "action": "blue"}},
    "Increase par":{"method": "Input.ExecuteAction","params":{ "action": "increasepar"}},
    "Decrease par":{"method": "Input.ExecuteAction","params":{ "action": "decreasepar"}},
    "Vol amp up":{"method": "Input.ExecuteAction","params":{ "action": "volampup"}},
    "Vol amp down":{"method": "Input.ExecuteAction","params":{ "action": "volampdown"}},
    "Volume amplification":{"method": "Input.ExecuteAction","params":{ "action": "volumeamplification"}},
    "Create bookmark":{"method": "Input.ExecuteAction","params":{ "action": "createbookmark"}},
    "Create episode bookmark":{"method": "Input.ExecuteAction","params":{ "action": "createepisodebookmark"}},
    "Settings reset":{"method": "Input.ExecuteAction","params":{ "action": "settingsreset"}},
    "Settings level change":{"method": "Input.ExecuteAction","params":{ "action": "settingslevelchange"}},
    "Stereo mode":{"method": "Input.ExecuteAction","params":{ "action": "stereomode"}},
    "Next stereo mode":{"method": "Input.ExecuteAction","params":{ "action": "nextstereomode"}},
    "Previous stereo mode":{"method": "Input.ExecuteAction","params":{ "action": "previousstereomode"}},
    "Toggle stereo mode":{"method": "Input.ExecuteAction","params":{ "action": "togglestereomode"}},
    "Stereo mode to mono":{"method": "Input.ExecuteAction","params":{ "action": "stereomodetomono"}},
    "Previous channel group":{"method": "Input.ExecuteAction","params":{ "action": "previouschannelgroup"}},
    "Next channel group":{"method": "Input.ExecuteAction","params":{ "action": "nextchannelgroup"}},
    "Play pvr":{"method": "Input.ExecuteAction","params":{ "action": "playpvr"}},
    "Play pvr tv":{"method": "Input.ExecuteAction","params":{ "action": "playpvrtv"}},
    "Play pvr radio":{"method": "Input.ExecuteAction","params":{ "action": "playpvrradio"}},
    "Record":{"method": "Input.ExecuteAction","params":{ "action": "record"}},
    "Toggle comm skip":{"method": "Input.ExecuteAction","params":{ "action": "togglecommskip"}},
    "Show timerrule":{"method": "Input.ExecuteAction","params":{ "action": "showtimerrule"}},
    "Leftclick":{"method": "Input.ExecuteAction","params":{ "action": "leftclick"}},
    "Rightclick":{"method": "Input.ExecuteAction","params":{ "action": "rightclick"}},
    "Middleclick":{"method": "Input.ExecuteAction","params":{ "action": "middleclick"}},
    "Doubleclick":{"method": "Input.ExecuteAction","params":{ "action": "doubleclick"}},
    "Longclick":{"method": "Input.ExecuteAction","params":{ "action": "longclick"}},
    "Wheelup":{"method": "Input.ExecuteAction","params":{ "action": "wheelup"}},
    "Wheeldown":{"method": "Input.ExecuteAction","params":{ "action": "wheeldown"}},
    "Mousedrag":{"method": "Input.ExecuteAction","params":{ "action": "mousedrag"}},
    "Mousemove":{"method": "Input.ExecuteAction","params":{ "action": "mousemove"}},
    "Tap":{"method": "Input.ExecuteAction","params":{ "action": "tap"}},
    "Longpress":{"method": "Input.ExecuteAction","params":{ "action": "longpress"}},
    "Pangesture":{"method": "Input.ExecuteAction","params":{ "action": "pangesture"}},
    "Zoomgesture":{"method": "Input.ExecuteAction","params":{ "action": "zoomgesture"}},
    "Rotategesture":{"method": "Input.ExecuteAction","params":{ "action": "rotategesture"}},
    "Swipe left":{"method": "Input.ExecuteAction","params":{ "action": "swipeleft"}},
    "Swipe right":{"method": "Input.ExecuteAction","params":{ "action": "swiperight"}},
    "Swipe up":{"method": "Input.ExecuteAction","params":{ "action": "swipeup"}},
    "Swipe down":{"method": "Input.ExecuteAction","params":{ "action": "swipedown"}},
    "Error":{"method": "Input.ExecuteAction","params":{ "action": "error"}},
    "Noop":{"method": "Input.ExecuteAction","params":{ "action": "noop"}}
  }
}

